import Head from "next/head";

import Banner from "@/components/banner/Banner";
import NavBar from "@/components/navbar/NavBar";
import SectionCards from "@/components/card/SectionCards";
import { getVideos } from "@/lib/videos";

import styles from "@/styles/Home.module.css";

export const getServerSideProps = async () => {
  const videoList = getVideos();

  return { props: { videoList }};
};

export default function Home({ videoList }) {
  return (
    <>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="Sora" />
      <Banner title="Anime" subTitle="Fun Anime" imageURL="/static/ayaka.jpg" />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Anime" videos={videoList} size="large" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCards title="Anime2" videos={videoList} size="medium" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCards title="Anime3" videos={videoList} size="small" />
      </div>
    </>
  );
}
