import Head from "next/head";

import Banner from "@/components/banner/Banner";
import NavBar from "@/components/navbar/NavBar";
import SectionCards from "@/components/card/SectionCards";
import { getVideos } from "@/lib/videos";

import styles from "@/styles/Home.module.css";

export const getServerSideProps = async (context) => {
  const category = 'anime%20trailers';

  const animeList = await getVideos("anime%20trailers");
  const genshinList = await getVideos("genshin%20impact");
  // const popularList = await getVideos("");
  const productivityList = await getVideos("productivity");

  return { props: { animeList, genshinList, productivityList }};
};

export default function Home({ animeList, genshinList, productivityList }) {
  return (
    <>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="Sora" />
      <Banner title="Kamisato Ayaka" subTitle="Fun Anime" imageURL="/static/ayaka.jpg" />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Anime Trailers" videos={animeList} size="large" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCards title="Genshin Impact" videos={genshinList} size="medium" />
      </div>
      {/* <div className={styles.sectionWrapper}>
        <SectionCards title="Popular/Trending" videos={popularList} size="small" />
      </div> */}
      <div className={styles.sectionWrapper}>
        <SectionCards title="Productivity" videos={productivityList} size="small" />
      </div>
    </>
  );
}
